---
# tasks file for ansible-freeipa-client

- name: Assert supported distribution
  tags:
    - assertion
    - freeipaclient
  assert:
    that:
      - ansible_distribution + '-' + ansible_distribution_major_version in freeipaclient_supported_distributions

- name: Import variables
  tags:
    - import
  include_vars: "{{ ansible_distribution }}.yml"

#I expect this to break if network manager
#or other script
#is handling the /etc/resolv.conf file.
- name: Set DNS server
  tags:
    - dns
  become: true
  when: freeipaclient_dns_server is defined
  lineinfile:
    state: present
    line: "nameserver {{ freeipaclient_dns_server }}"
    dest: /etc/resolv.conf
    backup: yes

- name: Install required packages
  package: 
    state: present
    name: "{{ item }}"
    update_cache: yes
  tags:
    - packagemanagement
  become: true
  with_items: "{{ packages }}"

- name: Check if host is enrolled
  tags:
    - enroll
  register: freeipaclient_ipaconf
  always_run: true
  stat:
    path=/etc/ipa/default.conf

#ntpd config will fail if chronyd is in use
- name: disable chronyd
  service:
    name: chronyd
    state: stopped
    enabled: no

- name: ensure /var/log/sssd directory exists
  file: 
    path: /var/log/sssd
    mode: 0755
    group: root
    owner: root
    state: directory
 
- name: uninstall ipa client
  command: "ipa-client-install --uninstall -U"
  ignore_errors: yes

- name: Enroll host in domain
  tags:
    - enroll
  become: true
  when: not freeipaclient_ipaconf.stat.exists
  register: freeipaclient_enrollment
  command: "{{ freeipaclient_install_command }}
          {{'--hostname=' + freeipaclient_hostname  if freeipaclient_hostname is defined else ''}}
          --server={{ freeipaclient_server }}
          --domain={{ freeipaclient_domain }}
          --principal={{ freeipaclient_enroll_user }}
          --password={{ freeipaclient_enroll_pass }}
          --ssh-trust-dns
          --unattended
          {{ '--all-ip-addresses' if freeipaclient_all_ip_addresses else ''}}
          {{ '--no-ntp' if not freeipaclient_enable_ntp else ''}}
          {{ '--force-join --force' if freeipaclient_force_join else ''}}"

- name: Include distribution specific tasks
  include: "{{ansible_os_family|lower}}.yml"
